import zipfile
zipf = zipfile.ZipFile("Colin.zip", 'w')
zipf = zipfile.ZipFile("Colin1.zip", 'w')
zipf = zipfile.ZipFile("Colin2.zip", 'w')
zipf = zipfile.ZipFile("Colin3.zip", 'w')
zipf = zipfile.ZipFile("Colin4.zip", 'w')
zipf = zipfile.ZipFile("Colin5.zip", 'w')
zipf = zipfile.ZipFile("Colin6.zip", 'w')
zipf.close()
print("Zip Fayllar Yaratildi!")
